/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicioempleodigital.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import servicioempleodigital.model.Respuesta;
import servicioempleodigital.model.RespuestaModel;
import servicioempleodigital.model.RespuestaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Respuesta service. Represents a row in the &quot;FOO_Respuesta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link RespuestaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RespuestaImpl}.
 * </p>
 *
 * @author Francisco de Borja Segovia Gilsanz
 * @see RespuestaImpl
 * @see Respuesta
 * @see RespuestaModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class RespuestaModelImpl extends BaseModelImpl<Respuesta>
	implements RespuestaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a respuesta model instance should use the {@link Respuesta} interface instead.
	 */
	public static final String TABLE_NAME = "FOO_Respuesta";
	public static final Object[][] TABLE_COLUMNS = {
			{ "idRespuesta", Types.BIGINT },
			{ "respuesta", Types.VARCHAR },
			{ "valor", Types.DOUBLE },
			{ "idPregunta", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("idRespuesta", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("respuesta", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("valor", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("idPregunta", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table FOO_Respuesta (idRespuesta LONG not null primary key IDENTITY,respuesta VARCHAR(75) null,valor DOUBLE,idPregunta LONG)";
	public static final String TABLE_SQL_DROP = "drop table FOO_Respuesta";
	public static final String ORDER_BY_JPQL = " ORDER BY respuesta.idRespuesta ASC";
	public static final String ORDER_BY_SQL = " ORDER BY FOO_Respuesta.idRespuesta ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(servicioempleodigital.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.servicioempleodigital.model.Respuesta"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(servicioempleodigital.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.servicioempleodigital.model.Respuesta"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Respuesta toModel(RespuestaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Respuesta model = new RespuestaImpl();

		model.setIdRespuesta(soapModel.getIdRespuesta());
		model.setRespuesta(soapModel.getRespuesta());
		model.setValor(soapModel.getValor());
		model.setIdPregunta(soapModel.getIdPregunta());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Respuesta> toModels(RespuestaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Respuesta> models = new ArrayList<Respuesta>(soapModels.length);

		for (RespuestaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(servicioempleodigital.service.util.ServiceProps.get(
				"lock.expiration.time.servicioempleodigital.model.Respuesta"));

	public RespuestaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idRespuesta;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdRespuesta(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idRespuesta;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Respuesta.class;
	}

	@Override
	public String getModelClassName() {
		return Respuesta.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("idRespuesta", getIdRespuesta());
		attributes.put("respuesta", getRespuesta());
		attributes.put("valor", getValor());
		attributes.put("idPregunta", getIdPregunta());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long idRespuesta = (Long)attributes.get("idRespuesta");

		if (idRespuesta != null) {
			setIdRespuesta(idRespuesta);
		}

		String respuesta = (String)attributes.get("respuesta");

		if (respuesta != null) {
			setRespuesta(respuesta);
		}

		Double valor = (Double)attributes.get("valor");

		if (valor != null) {
			setValor(valor);
		}

		Long idPregunta = (Long)attributes.get("idPregunta");

		if (idPregunta != null) {
			setIdPregunta(idPregunta);
		}
	}

	@JSON
	@Override
	public long getIdRespuesta() {
		return _idRespuesta;
	}

	@Override
	public void setIdRespuesta(long idRespuesta) {
		_idRespuesta = idRespuesta;
	}

	@JSON
	@Override
	public String getRespuesta() {
		if (_respuesta == null) {
			return StringPool.BLANK;
		}
		else {
			return _respuesta;
		}
	}

	@Override
	public void setRespuesta(String respuesta) {
		_respuesta = respuesta;
	}

	@JSON
	@Override
	public double getValor() {
		return _valor;
	}

	@Override
	public void setValor(double valor) {
		_valor = valor;
	}

	@JSON
	@Override
	public long getIdPregunta() {
		return _idPregunta;
	}

	@Override
	public void setIdPregunta(long idPregunta) {
		_idPregunta = idPregunta;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Respuesta.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Respuesta toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Respuesta)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RespuestaImpl respuestaImpl = new RespuestaImpl();

		respuestaImpl.setIdRespuesta(getIdRespuesta());
		respuestaImpl.setRespuesta(getRespuesta());
		respuestaImpl.setValor(getValor());
		respuestaImpl.setIdPregunta(getIdPregunta());

		respuestaImpl.resetOriginalValues();

		return respuestaImpl;
	}

	@Override
	public int compareTo(Respuesta respuesta) {
		long primaryKey = respuesta.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Respuesta)) {
			return false;
		}

		Respuesta respuesta = (Respuesta)obj;

		long primaryKey = respuesta.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Respuesta> toCacheModel() {
		RespuestaCacheModel respuestaCacheModel = new RespuestaCacheModel();

		respuestaCacheModel.idRespuesta = getIdRespuesta();

		respuestaCacheModel.respuesta = getRespuesta();

		String respuesta = respuestaCacheModel.respuesta;

		if ((respuesta != null) && (respuesta.length() == 0)) {
			respuestaCacheModel.respuesta = null;
		}

		respuestaCacheModel.valor = getValor();

		respuestaCacheModel.idPregunta = getIdPregunta();

		return respuestaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{idRespuesta=");
		sb.append(getIdRespuesta());
		sb.append(", respuesta=");
		sb.append(getRespuesta());
		sb.append(", valor=");
		sb.append(getValor());
		sb.append(", idPregunta=");
		sb.append(getIdPregunta());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("servicioempleodigital.model.Respuesta");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>idRespuesta</column-name><column-value><![CDATA[");
		sb.append(getIdRespuesta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>respuesta</column-name><column-value><![CDATA[");
		sb.append(getRespuesta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>valor</column-name><column-value><![CDATA[");
		sb.append(getValor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idPregunta</column-name><column-value><![CDATA[");
		sb.append(getIdPregunta());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Respuesta.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Respuesta.class
		};
	private long _idRespuesta;
	private String _respuesta;
	private double _valor;
	private long _idPregunta;
	private Respuesta _escapedModel;
}