/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicioempleodigital.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Candidato service. Represents a row in the &quot;FOO_Candidato&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servicioempleodigital.model.impl.CandidatoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servicioempleodigital.model.impl.CandidatoImpl}.
 * </p>
 *
 * @author Francisco de Borja Segovia Gilsanz
 * @see Candidato
 * @see servicioempleodigital.model.impl.CandidatoImpl
 * @see servicioempleodigital.model.impl.CandidatoModelImpl
 * @generated
 */
@ProviderType
public interface CandidatoModel extends BaseModel<Candidato> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a candidato model instance should use the {@link Candidato} interface instead.
	 */

	/**
	 * Returns the primary key of this candidato.
	 *
	 * @return the primary key of this candidato
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this candidato.
	 *
	 * @param primaryKey the primary key of this candidato
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id candidato of this candidato.
	 *
	 * @return the id candidato of this candidato
	 */
	public long getIdCandidato();

	/**
	 * Sets the id candidato of this candidato.
	 *
	 * @param idCandidato the id candidato of this candidato
	 */
	public void setIdCandidato(long idCandidato);

	/**
	 * Returns the nif of this candidato.
	 *
	 * @return the nif of this candidato
	 */
	@AutoEscape
	public String getNif();

	/**
	 * Sets the nif of this candidato.
	 *
	 * @param nif the nif of this candidato
	 */
	public void setNif(String nif);

	/**
	 * Returns the nombre of this candidato.
	 *
	 * @return the nombre of this candidato
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this candidato.
	 *
	 * @param nombre the nombre of this candidato
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the apellidos of this candidato.
	 *
	 * @return the apellidos of this candidato
	 */
	@AutoEscape
	public String getApellidos();

	/**
	 * Sets the apellidos of this candidato.
	 *
	 * @param apellidos the apellidos of this candidato
	 */
	public void setApellidos(String apellidos);

	/**
	 * Returns the fecha de nacimiento of this candidato.
	 *
	 * @return the fecha de nacimiento of this candidato
	 */
	public Date getFechaDeNacimiento();

	/**
	 * Sets the fecha de nacimiento of this candidato.
	 *
	 * @param fechaDeNacimiento the fecha de nacimiento of this candidato
	 */
	public void setFechaDeNacimiento(Date fechaDeNacimiento);

	/**
	 * Returns the email of this candidato.
	 *
	 * @return the email of this candidato
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this candidato.
	 *
	 * @param email the email of this candidato
	 */
	public void setEmail(String email);

	/**
	 * Returns the telefono of this candidato.
	 *
	 * @return the telefono of this candidato
	 */
	@AutoEscape
	public String getTelefono();

	/**
	 * Sets the telefono of this candidato.
	 *
	 * @param telefono the telefono of this candidato
	 */
	public void setTelefono(String telefono);

	/**
	 * Returns the password of this candidato.
	 *
	 * @return the password of this candidato
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this candidato.
	 *
	 * @param password the password of this candidato
	 */
	public void setPassword(String password);

	/**
	 * Returns the provincia of this candidato.
	 *
	 * @return the provincia of this candidato
	 */
	public int getProvincia();

	/**
	 * Sets the provincia of this candidato.
	 *
	 * @param provincia the provincia of this candidato
	 */
	public void setProvincia(int provincia);

	/**
	 * Returns the ciudad of this candidato.
	 *
	 * @return the ciudad of this candidato
	 */
	@AutoEscape
	public String getCiudad();

	/**
	 * Sets the ciudad of this candidato.
	 *
	 * @param ciudad the ciudad of this candidato
	 */
	public void setCiudad(String ciudad);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(servicioempleodigital.model.Candidato candidato);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servicioempleodigital.model.Candidato> toCacheModel();

	@Override
	public servicioempleodigital.model.Candidato toEscapedModel();

	@Override
	public servicioempleodigital.model.Candidato toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}