/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicioempleodigital.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Oferta service. Represents a row in the &quot;FOO_Oferta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servicioempleodigital.model.impl.OfertaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servicioempleodigital.model.impl.OfertaImpl}.
 * </p>
 *
 * @author Francisco de Borja Segovia Gilsanz
 * @see Oferta
 * @see servicioempleodigital.model.impl.OfertaImpl
 * @see servicioempleodigital.model.impl.OfertaModelImpl
 * @generated
 */
@ProviderType
public interface OfertaModel extends BaseModel<Oferta> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a oferta model instance should use the {@link Oferta} interface instead.
	 */

	/**
	 * Returns the primary key of this oferta.
	 *
	 * @return the primary key of this oferta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this oferta.
	 *
	 * @param primaryKey the primary key of this oferta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id oferta of this oferta.
	 *
	 * @return the id oferta of this oferta
	 */
	public long getIdOferta();

	/**
	 * Sets the id oferta of this oferta.
	 *
	 * @param idOferta the id oferta of this oferta
	 */
	public void setIdOferta(long idOferta);

	/**
	 * Returns the titulo of this oferta.
	 *
	 * @return the titulo of this oferta
	 */
	@AutoEscape
	public String getTitulo();

	/**
	 * Sets the titulo of this oferta.
	 *
	 * @param titulo the titulo of this oferta
	 */
	public void setTitulo(String titulo);

	/**
	 * Returns the descripcion of this oferta.
	 *
	 * @return the descripcion of this oferta
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this oferta.
	 *
	 * @param descripcion the descripcion of this oferta
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the provincia of this oferta.
	 *
	 * @return the provincia of this oferta
	 */
	public int getProvincia();

	/**
	 * Sets the provincia of this oferta.
	 *
	 * @param provincia the provincia of this oferta
	 */
	public void setProvincia(int provincia);

	/**
	 * Returns the ciudad of this oferta.
	 *
	 * @return the ciudad of this oferta
	 */
	@AutoEscape
	public String getCiudad();

	/**
	 * Sets the ciudad of this oferta.
	 *
	 * @param ciudad the ciudad of this oferta
	 */
	public void setCiudad(String ciudad);

	/**
	 * Returns the salario of this oferta.
	 *
	 * @return the salario of this oferta
	 */
	@AutoEscape
	public String getSalario();

	/**
	 * Sets the salario of this oferta.
	 *
	 * @param salario the salario of this oferta
	 */
	public void setSalario(String salario);

	/**
	 * Returns the fecha inicio of this oferta.
	 *
	 * @return the fecha inicio of this oferta
	 */
	public Date getFechaInicio();

	/**
	 * Sets the fecha inicio of this oferta.
	 *
	 * @param fechaInicio the fecha inicio of this oferta
	 */
	public void setFechaInicio(Date fechaInicio);

	/**
	 * Returns the fecha modificacion of this oferta.
	 *
	 * @return the fecha modificacion of this oferta
	 */
	public Date getFechaModificacion();

	/**
	 * Sets the fecha modificacion of this oferta.
	 *
	 * @param fechaModificacion the fecha modificacion of this oferta
	 */
	public void setFechaModificacion(Date fechaModificacion);

	/**
	 * Returns the fecha fin of this oferta.
	 *
	 * @return the fecha fin of this oferta
	 */
	public Date getFechaFin();

	/**
	 * Sets the fecha fin of this oferta.
	 *
	 * @param fechaFin the fecha fin of this oferta
	 */
	public void setFechaFin(Date fechaFin);

	/**
	 * Returns the plazas of this oferta.
	 *
	 * @return the plazas of this oferta
	 */
	public int getPlazas();

	/**
	 * Sets the plazas of this oferta.
	 *
	 * @param plazas the plazas of this oferta
	 */
	public void setPlazas(int plazas);

	/**
	 * Returns the candidatos of this oferta.
	 *
	 * @return the candidatos of this oferta
	 */
	public int getCandidatos();

	/**
	 * Sets the candidatos of this oferta.
	 *
	 * @param candidatos the candidatos of this oferta
	 */
	public void setCandidatos(int candidatos);

	/**
	 * Returns the requisitos minimos of this oferta.
	 *
	 * @return the requisitos minimos of this oferta
	 */
	@AutoEscape
	public String getRequisitosMinimos();

	/**
	 * Sets the requisitos minimos of this oferta.
	 *
	 * @param requisitosMinimos the requisitos minimos of this oferta
	 */
	public void setRequisitosMinimos(String requisitosMinimos);

	/**
	 * Returns the requisitos opcionales of this oferta.
	 *
	 * @return the requisitos opcionales of this oferta
	 */
	@AutoEscape
	public String getRequisitosOpcionales();

	/**
	 * Sets the requisitos opcionales of this oferta.
	 *
	 * @param requisitosOpcionales the requisitos opcionales of this oferta
	 */
	public void setRequisitosOpcionales(String requisitosOpcionales);

	/**
	 * Returns the activa of this oferta.
	 *
	 * @return the activa of this oferta
	 */
	public boolean getActiva();

	/**
	 * Returns <code>true</code> if this oferta is activa.
	 *
	 * @return <code>true</code> if this oferta is activa; <code>false</code> otherwise
	 */
	public boolean isActiva();

	/**
	 * Sets whether this oferta is activa.
	 *
	 * @param activa the activa of this oferta
	 */
	public void setActiva(boolean activa);

	/**
	 * Returns the id empresa of this oferta.
	 *
	 * @return the id empresa of this oferta
	 */
	public long getIdEmpresa();

	/**
	 * Sets the id empresa of this oferta.
	 *
	 * @param idEmpresa the id empresa of this oferta
	 */
	public void setIdEmpresa(long idEmpresa);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(servicioempleodigital.model.Oferta oferta);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servicioempleodigital.model.Oferta> toCacheModel();

	@Override
	public servicioempleodigital.model.Oferta toEscapedModel();

	@Override
	public servicioempleodigital.model.Oferta toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}