/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicioempleodigital.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Pregunta service. Represents a row in the &quot;FOO_Pregunta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servicioempleodigital.model.impl.PreguntaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servicioempleodigital.model.impl.PreguntaImpl}.
 * </p>
 *
 * @author Francisco de Borja Segovia Gilsanz
 * @see Pregunta
 * @see servicioempleodigital.model.impl.PreguntaImpl
 * @see servicioempleodigital.model.impl.PreguntaModelImpl
 * @generated
 */
@ProviderType
public interface PreguntaModel extends BaseModel<Pregunta> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pregunta model instance should use the {@link Pregunta} interface instead.
	 */

	/**
	 * Returns the primary key of this pregunta.
	 *
	 * @return the primary key of this pregunta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pregunta.
	 *
	 * @param primaryKey the primary key of this pregunta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id pregunta of this pregunta.
	 *
	 * @return the id pregunta of this pregunta
	 */
	public long getIdPregunta();

	/**
	 * Sets the id pregunta of this pregunta.
	 *
	 * @param idPregunta the id pregunta of this pregunta
	 */
	public void setIdPregunta(long idPregunta);

	/**
	 * Returns the enunciado of this pregunta.
	 *
	 * @return the enunciado of this pregunta
	 */
	@AutoEscape
	public String getEnunciado();

	/**
	 * Sets the enunciado of this pregunta.
	 *
	 * @param enunciado the enunciado of this pregunta
	 */
	public void setEnunciado(String enunciado);

	/**
	 * Returns the tipo of this pregunta.
	 *
	 * @return the tipo of this pregunta
	 */
	public int getTipo();

	/**
	 * Sets the tipo of this pregunta.
	 *
	 * @param tipo the tipo of this pregunta
	 */
	public void setTipo(int tipo);

	/**
	 * Returns the id oferta of this pregunta.
	 *
	 * @return the id oferta of this pregunta
	 */
	public long getIdOferta();

	/**
	 * Sets the id oferta of this pregunta.
	 *
	 * @param idOferta the id oferta of this pregunta
	 */
	public void setIdOferta(long idOferta);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(servicioempleodigital.model.Pregunta pregunta);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servicioempleodigital.model.Pregunta> toCacheModel();

	@Override
	public servicioempleodigital.model.Pregunta toEscapedModel();

	@Override
	public servicioempleodigital.model.Pregunta toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}