/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicioempleodigital.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import servicioempleodigital.service.persistence.RespondidaPK;

import java.io.Serializable;

/**
 * The base model interface for the Respondida service. Represents a row in the &quot;FOO_Respondida&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servicioempleodigital.model.impl.RespondidaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servicioempleodigital.model.impl.RespondidaImpl}.
 * </p>
 *
 * @author Francisco de Borja Segovia Gilsanz
 * @see Respondida
 * @see servicioempleodigital.model.impl.RespondidaImpl
 * @see servicioempleodigital.model.impl.RespondidaModelImpl
 * @generated
 */
@ProviderType
public interface RespondidaModel extends BaseModel<Respondida> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a respondida model instance should use the {@link Respondida} interface instead.
	 */

	/**
	 * Returns the primary key of this respondida.
	 *
	 * @return the primary key of this respondida
	 */
	public RespondidaPK getPrimaryKey();

	/**
	 * Sets the primary key of this respondida.
	 *
	 * @param primaryKey the primary key of this respondida
	 */
	public void setPrimaryKey(RespondidaPK primaryKey);

	/**
	 * Returns the id respuesta of this respondida.
	 *
	 * @return the id respuesta of this respondida
	 */
	public long getIdRespuesta();

	/**
	 * Sets the id respuesta of this respondida.
	 *
	 * @param idRespuesta the id respuesta of this respondida
	 */
	public void setIdRespuesta(long idRespuesta);

	/**
	 * Returns the id candidato of this respondida.
	 *
	 * @return the id candidato of this respondida
	 */
	public long getIdCandidato();

	/**
	 * Sets the id candidato of this respondida.
	 *
	 * @param idCandidato the id candidato of this respondida
	 */
	public void setIdCandidato(long idCandidato);

	/**
	 * Returns the respuesta of this respondida.
	 *
	 * @return the respuesta of this respondida
	 */
	@AutoEscape
	public String getRespuesta();

	/**
	 * Sets the respuesta of this respondida.
	 *
	 * @param respuesta the respuesta of this respondida
	 */
	public void setRespuesta(String respuesta);

	/**
	 * Returns the respondida of this respondida.
	 *
	 * @return the respondida of this respondida
	 */
	public boolean getRespondida();

	/**
	 * Returns <code>true</code> if this respondida is respondida.
	 *
	 * @return <code>true</code> if this respondida is respondida; <code>false</code> otherwise
	 */
	public boolean isRespondida();

	/**
	 * Sets whether this respondida is respondida.
	 *
	 * @param respondida the respondida of this respondida
	 */
	public void setRespondida(boolean respondida);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(servicioempleodigital.model.Respondida respondida);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servicioempleodigital.model.Respondida> toCacheModel();

	@Override
	public servicioempleodigital.model.Respondida toEscapedModel();

	@Override
	public servicioempleodigital.model.Respondida toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}