/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicioempleodigital.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import servicioempleodigital.service.persistence.ResultadoPK;

import java.io.Serializable;

/**
 * The base model interface for the Resultado service. Represents a row in the &quot;FOO_Resultado&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servicioempleodigital.model.impl.ResultadoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servicioempleodigital.model.impl.ResultadoImpl}.
 * </p>
 *
 * @author Francisco de Borja Segovia Gilsanz
 * @see Resultado
 * @see servicioempleodigital.model.impl.ResultadoImpl
 * @see servicioempleodigital.model.impl.ResultadoModelImpl
 * @generated
 */
@ProviderType
public interface ResultadoModel extends BaseModel<Resultado> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a resultado model instance should use the {@link Resultado} interface instead.
	 */

	/**
	 * Returns the primary key of this resultado.
	 *
	 * @return the primary key of this resultado
	 */
	public ResultadoPK getPrimaryKey();

	/**
	 * Sets the primary key of this resultado.
	 *
	 * @param primaryKey the primary key of this resultado
	 */
	public void setPrimaryKey(ResultadoPK primaryKey);

	/**
	 * Returns the puntuacion of this resultado.
	 *
	 * @return the puntuacion of this resultado
	 */
	public double getPuntuacion();

	/**
	 * Sets the puntuacion of this resultado.
	 *
	 * @param puntuacion the puntuacion of this resultado
	 */
	public void setPuntuacion(double puntuacion);

	/**
	 * Returns the id candidato of this resultado.
	 *
	 * @return the id candidato of this resultado
	 */
	public long getIdCandidato();

	/**
	 * Sets the id candidato of this resultado.
	 *
	 * @param idCandidato the id candidato of this resultado
	 */
	public void setIdCandidato(long idCandidato);

	/**
	 * Returns the id oferta of this resultado.
	 *
	 * @return the id oferta of this resultado
	 */
	public long getIdOferta();

	/**
	 * Sets the id oferta of this resultado.
	 *
	 * @param idOferta the id oferta of this resultado
	 */
	public void setIdOferta(long idOferta);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(servicioempleodigital.model.Resultado resultado);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servicioempleodigital.model.Resultado> toCacheModel();

	@Override
	public servicioempleodigital.model.Resultado toEscapedModel();

	@Override
	public servicioempleodigital.model.Resultado toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}