/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicioempleodigital.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import servicioempleodigital.model.Oferta;

import servicioempleodigital.service.OfertaService;

import servicioempleodigital.service.persistence.CandidatoPersistence;
import servicioempleodigital.service.persistence.EmpresaPersistence;
import servicioempleodigital.service.persistence.OfertaPersistence;
import servicioempleodigital.service.persistence.PreguntaPersistence;
import servicioempleodigital.service.persistence.RespondidaPersistence;
import servicioempleodigital.service.persistence.RespuestaPersistence;
import servicioempleodigital.service.persistence.ResultadoPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the oferta remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link servicioempleodigital.service.impl.OfertaServiceImpl}.
 * </p>
 *
 * @author Francisco de Borja Segovia Gilsanz
 * @see servicioempleodigital.service.impl.OfertaServiceImpl
 * @see servicioempleodigital.service.OfertaServiceUtil
 * @generated
 */
public abstract class OfertaServiceBaseImpl extends BaseServiceImpl
	implements OfertaService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link servicioempleodigital.service.OfertaServiceUtil} to access the oferta remote service.
	 */

	/**
	 * Returns the candidato local service.
	 *
	 * @return the candidato local service
	 */
	public servicioempleodigital.service.CandidatoLocalService getCandidatoLocalService() {
		return candidatoLocalService;
	}

	/**
	 * Sets the candidato local service.
	 *
	 * @param candidatoLocalService the candidato local service
	 */
	public void setCandidatoLocalService(
		servicioempleodigital.service.CandidatoLocalService candidatoLocalService) {
		this.candidatoLocalService = candidatoLocalService;
	}

	/**
	 * Returns the candidato remote service.
	 *
	 * @return the candidato remote service
	 */
	public servicioempleodigital.service.CandidatoService getCandidatoService() {
		return candidatoService;
	}

	/**
	 * Sets the candidato remote service.
	 *
	 * @param candidatoService the candidato remote service
	 */
	public void setCandidatoService(
		servicioempleodigital.service.CandidatoService candidatoService) {
		this.candidatoService = candidatoService;
	}

	/**
	 * Returns the candidato persistence.
	 *
	 * @return the candidato persistence
	 */
	public CandidatoPersistence getCandidatoPersistence() {
		return candidatoPersistence;
	}

	/**
	 * Sets the candidato persistence.
	 *
	 * @param candidatoPersistence the candidato persistence
	 */
	public void setCandidatoPersistence(
		CandidatoPersistence candidatoPersistence) {
		this.candidatoPersistence = candidatoPersistence;
	}

	/**
	 * Returns the empresa local service.
	 *
	 * @return the empresa local service
	 */
	public servicioempleodigital.service.EmpresaLocalService getEmpresaLocalService() {
		return empresaLocalService;
	}

	/**
	 * Sets the empresa local service.
	 *
	 * @param empresaLocalService the empresa local service
	 */
	public void setEmpresaLocalService(
		servicioempleodigital.service.EmpresaLocalService empresaLocalService) {
		this.empresaLocalService = empresaLocalService;
	}

	/**
	 * Returns the empresa remote service.
	 *
	 * @return the empresa remote service
	 */
	public servicioempleodigital.service.EmpresaService getEmpresaService() {
		return empresaService;
	}

	/**
	 * Sets the empresa remote service.
	 *
	 * @param empresaService the empresa remote service
	 */
	public void setEmpresaService(
		servicioempleodigital.service.EmpresaService empresaService) {
		this.empresaService = empresaService;
	}

	/**
	 * Returns the empresa persistence.
	 *
	 * @return the empresa persistence
	 */
	public EmpresaPersistence getEmpresaPersistence() {
		return empresaPersistence;
	}

	/**
	 * Sets the empresa persistence.
	 *
	 * @param empresaPersistence the empresa persistence
	 */
	public void setEmpresaPersistence(EmpresaPersistence empresaPersistence) {
		this.empresaPersistence = empresaPersistence;
	}

	/**
	 * Returns the oferta local service.
	 *
	 * @return the oferta local service
	 */
	public servicioempleodigital.service.OfertaLocalService getOfertaLocalService() {
		return ofertaLocalService;
	}

	/**
	 * Sets the oferta local service.
	 *
	 * @param ofertaLocalService the oferta local service
	 */
	public void setOfertaLocalService(
		servicioempleodigital.service.OfertaLocalService ofertaLocalService) {
		this.ofertaLocalService = ofertaLocalService;
	}

	/**
	 * Returns the oferta remote service.
	 *
	 * @return the oferta remote service
	 */
	public OfertaService getOfertaService() {
		return ofertaService;
	}

	/**
	 * Sets the oferta remote service.
	 *
	 * @param ofertaService the oferta remote service
	 */
	public void setOfertaService(OfertaService ofertaService) {
		this.ofertaService = ofertaService;
	}

	/**
	 * Returns the oferta persistence.
	 *
	 * @return the oferta persistence
	 */
	public OfertaPersistence getOfertaPersistence() {
		return ofertaPersistence;
	}

	/**
	 * Sets the oferta persistence.
	 *
	 * @param ofertaPersistence the oferta persistence
	 */
	public void setOfertaPersistence(OfertaPersistence ofertaPersistence) {
		this.ofertaPersistence = ofertaPersistence;
	}

	/**
	 * Returns the pregunta local service.
	 *
	 * @return the pregunta local service
	 */
	public servicioempleodigital.service.PreguntaLocalService getPreguntaLocalService() {
		return preguntaLocalService;
	}

	/**
	 * Sets the pregunta local service.
	 *
	 * @param preguntaLocalService the pregunta local service
	 */
	public void setPreguntaLocalService(
		servicioempleodigital.service.PreguntaLocalService preguntaLocalService) {
		this.preguntaLocalService = preguntaLocalService;
	}

	/**
	 * Returns the pregunta remote service.
	 *
	 * @return the pregunta remote service
	 */
	public servicioempleodigital.service.PreguntaService getPreguntaService() {
		return preguntaService;
	}

	/**
	 * Sets the pregunta remote service.
	 *
	 * @param preguntaService the pregunta remote service
	 */
	public void setPreguntaService(
		servicioempleodigital.service.PreguntaService preguntaService) {
		this.preguntaService = preguntaService;
	}

	/**
	 * Returns the pregunta persistence.
	 *
	 * @return the pregunta persistence
	 */
	public PreguntaPersistence getPreguntaPersistence() {
		return preguntaPersistence;
	}

	/**
	 * Sets the pregunta persistence.
	 *
	 * @param preguntaPersistence the pregunta persistence
	 */
	public void setPreguntaPersistence(PreguntaPersistence preguntaPersistence) {
		this.preguntaPersistence = preguntaPersistence;
	}

	/**
	 * Returns the respondida local service.
	 *
	 * @return the respondida local service
	 */
	public servicioempleodigital.service.RespondidaLocalService getRespondidaLocalService() {
		return respondidaLocalService;
	}

	/**
	 * Sets the respondida local service.
	 *
	 * @param respondidaLocalService the respondida local service
	 */
	public void setRespondidaLocalService(
		servicioempleodigital.service.RespondidaLocalService respondidaLocalService) {
		this.respondidaLocalService = respondidaLocalService;
	}

	/**
	 * Returns the respondida remote service.
	 *
	 * @return the respondida remote service
	 */
	public servicioempleodigital.service.RespondidaService getRespondidaService() {
		return respondidaService;
	}

	/**
	 * Sets the respondida remote service.
	 *
	 * @param respondidaService the respondida remote service
	 */
	public void setRespondidaService(
		servicioempleodigital.service.RespondidaService respondidaService) {
		this.respondidaService = respondidaService;
	}

	/**
	 * Returns the respondida persistence.
	 *
	 * @return the respondida persistence
	 */
	public RespondidaPersistence getRespondidaPersistence() {
		return respondidaPersistence;
	}

	/**
	 * Sets the respondida persistence.
	 *
	 * @param respondidaPersistence the respondida persistence
	 */
	public void setRespondidaPersistence(
		RespondidaPersistence respondidaPersistence) {
		this.respondidaPersistence = respondidaPersistence;
	}

	/**
	 * Returns the respuesta local service.
	 *
	 * @return the respuesta local service
	 */
	public servicioempleodigital.service.RespuestaLocalService getRespuestaLocalService() {
		return respuestaLocalService;
	}

	/**
	 * Sets the respuesta local service.
	 *
	 * @param respuestaLocalService the respuesta local service
	 */
	public void setRespuestaLocalService(
		servicioempleodigital.service.RespuestaLocalService respuestaLocalService) {
		this.respuestaLocalService = respuestaLocalService;
	}

	/**
	 * Returns the respuesta remote service.
	 *
	 * @return the respuesta remote service
	 */
	public servicioempleodigital.service.RespuestaService getRespuestaService() {
		return respuestaService;
	}

	/**
	 * Sets the respuesta remote service.
	 *
	 * @param respuestaService the respuesta remote service
	 */
	public void setRespuestaService(
		servicioempleodigital.service.RespuestaService respuestaService) {
		this.respuestaService = respuestaService;
	}

	/**
	 * Returns the respuesta persistence.
	 *
	 * @return the respuesta persistence
	 */
	public RespuestaPersistence getRespuestaPersistence() {
		return respuestaPersistence;
	}

	/**
	 * Sets the respuesta persistence.
	 *
	 * @param respuestaPersistence the respuesta persistence
	 */
	public void setRespuestaPersistence(
		RespuestaPersistence respuestaPersistence) {
		this.respuestaPersistence = respuestaPersistence;
	}

	/**
	 * Returns the resultado local service.
	 *
	 * @return the resultado local service
	 */
	public servicioempleodigital.service.ResultadoLocalService getResultadoLocalService() {
		return resultadoLocalService;
	}

	/**
	 * Sets the resultado local service.
	 *
	 * @param resultadoLocalService the resultado local service
	 */
	public void setResultadoLocalService(
		servicioempleodigital.service.ResultadoLocalService resultadoLocalService) {
		this.resultadoLocalService = resultadoLocalService;
	}

	/**
	 * Returns the resultado remote service.
	 *
	 * @return the resultado remote service
	 */
	public servicioempleodigital.service.ResultadoService getResultadoService() {
		return resultadoService;
	}

	/**
	 * Sets the resultado remote service.
	 *
	 * @param resultadoService the resultado remote service
	 */
	public void setResultadoService(
		servicioempleodigital.service.ResultadoService resultadoService) {
		this.resultadoService = resultadoService;
	}

	/**
	 * Returns the resultado persistence.
	 *
	 * @return the resultado persistence
	 */
	public ResultadoPersistence getResultadoPersistence() {
		return resultadoPersistence;
	}

	/**
	 * Sets the resultado persistence.
	 *
	 * @param resultadoPersistence the resultado persistence
	 */
	public void setResultadoPersistence(
		ResultadoPersistence resultadoPersistence) {
		this.resultadoPersistence = resultadoPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return OfertaService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Oferta.class;
	}

	protected String getModelClassName() {
		return Oferta.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = ofertaPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = servicioempleodigital.service.CandidatoLocalService.class)
	protected servicioempleodigital.service.CandidatoLocalService candidatoLocalService;
	@BeanReference(type = servicioempleodigital.service.CandidatoService.class)
	protected servicioempleodigital.service.CandidatoService candidatoService;
	@BeanReference(type = CandidatoPersistence.class)
	protected CandidatoPersistence candidatoPersistence;
	@BeanReference(type = servicioempleodigital.service.EmpresaLocalService.class)
	protected servicioempleodigital.service.EmpresaLocalService empresaLocalService;
	@BeanReference(type = servicioempleodigital.service.EmpresaService.class)
	protected servicioempleodigital.service.EmpresaService empresaService;
	@BeanReference(type = EmpresaPersistence.class)
	protected EmpresaPersistence empresaPersistence;
	@BeanReference(type = servicioempleodigital.service.OfertaLocalService.class)
	protected servicioempleodigital.service.OfertaLocalService ofertaLocalService;
	@BeanReference(type = OfertaService.class)
	protected OfertaService ofertaService;
	@BeanReference(type = OfertaPersistence.class)
	protected OfertaPersistence ofertaPersistence;
	@BeanReference(type = servicioempleodigital.service.PreguntaLocalService.class)
	protected servicioempleodigital.service.PreguntaLocalService preguntaLocalService;
	@BeanReference(type = servicioempleodigital.service.PreguntaService.class)
	protected servicioempleodigital.service.PreguntaService preguntaService;
	@BeanReference(type = PreguntaPersistence.class)
	protected PreguntaPersistence preguntaPersistence;
	@BeanReference(type = servicioempleodigital.service.RespondidaLocalService.class)
	protected servicioempleodigital.service.RespondidaLocalService respondidaLocalService;
	@BeanReference(type = servicioempleodigital.service.RespondidaService.class)
	protected servicioempleodigital.service.RespondidaService respondidaService;
	@BeanReference(type = RespondidaPersistence.class)
	protected RespondidaPersistence respondidaPersistence;
	@BeanReference(type = servicioempleodigital.service.RespuestaLocalService.class)
	protected servicioempleodigital.service.RespuestaLocalService respuestaLocalService;
	@BeanReference(type = servicioempleodigital.service.RespuestaService.class)
	protected servicioempleodigital.service.RespuestaService respuestaService;
	@BeanReference(type = RespuestaPersistence.class)
	protected RespuestaPersistence respuestaPersistence;
	@BeanReference(type = servicioempleodigital.service.ResultadoLocalService.class)
	protected servicioempleodigital.service.ResultadoLocalService resultadoLocalService;
	@BeanReference(type = servicioempleodigital.service.ResultadoService.class)
	protected servicioempleodigital.service.ResultadoService resultadoService;
	@BeanReference(type = ResultadoPersistence.class)
	protected ResultadoPersistence resultadoPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}